resolver: lts-14.6
compiler: ghc-8.9
allow-newer: true
system-ghc: true

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]

extra-deps:
  - primitive-0.7.0.0
  - streaming-0.2.3.0
  - git: https://github.com/tweag/linear-base.git
    commit: 6d85698940a66bd6f10113fbad1fa6b8ba82e7a0
