# Configures GHC to be the 8.2 variant from the Docker image
# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-12.2
compiler: ghc-8.5
allow-newer: true
system-ghc: true
docker:
  enable: true
  image: tweag/linear-types:0.1.9

packages:
- '.'
