# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-16.2
compiler: ghc-8.11
allow-newer: true
system-ghc: true

packages:
- '.'

extra-deps:
  - git: https://github.com/tweag/linear-base.git
    commit: c21edd4091c25873624e1e0246d81e5036fb174f

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
