# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-14.6
compiler: ghc-8.9
allow-newer: true
system-ghc: true

packages:
- '.'

# We must use a more recent version of primitive due to MonadFail
extra-deps:
  - primitive-0.7.0.0

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
