# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-16.2
compiler: ghc-8.11
allow-newer: true
system-ghc: true

packages:
- '.'

extra-deps:
- git: https://github.com/facundominguez/quickcheck.git
  commit: a498e7b41131cf7955b9e154ab26d37d1be10304
- git: https://github.com/facundominguez/lifted-async.git
  commit: 898eb485b21cc321058345998eedd8c409c326fd

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
