# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-14.6
compiler: ghc-8.9
allow-newer: true
system-ghc: true

packages:
- '.'

# We must use a more recent version of primitive due to MonadFail
# Hedgehog requires a newer version of constraints
extra-deps:
  - primitive-0.7.0.0
  - constraints-0.11
  - git: https://github.com/hedgehogqa/haskell-hedgehog.git
    commit: 3eaa0fa0140e565119f15ed4807e6e91e971c5ed
    subdirs:
      - hedgehog

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
