version: 2

jobs:
  build:
    docker:
      - image: tweag/linear-types:0.1.6
    environment:
      - stack: stack --no-docker
    steps:
      - checkout
      # Restore last version of the dependencies in cache
      # When a new major version of caches has to be generated,
      # please use vYYMMDD format to avoid collision.
      - restore_cache:
          key: linear-base-stackcache-{{ arch }}-v171204-
      - run:
          # --jobs=1 because of limitted memory
          name: Build dependencies
          command: |
            $stack build --jobs=1 --only-dependencies --no-haddock linear-base:lib
            $stack build --jobs=1 --test --bench --only-snapshot
            find . -name "*.cabal" -o -name "stack.yaml" -type f | xargs sha256sum > /tmp/dps_checksum
      - save_cache:
          key: linear-base-stackcache-{{ arch }}-v171204-{{ checksum "/tmp/dps_checksum" }}
          paths:
            - ~/.stack
      - run:
          name: Main build
          command: $stack build --pedantic
