version: 2

jobs:
  build:
    docker:
      - image: tweag/linear-types:1.0.5
    environment:
        # Changing this value will invalidate existing caches
        CACHE_VERSION: "2019-08-25"
    steps:
      - checkout
      - run:
          name: Load cache version
          command: echo "$CACHE_VERSION" > _cache_v
      # Restore last version of the dependencies in cache
      - restore_cache:
          keys:
          - linear-base-stackcache-{{ arch }}-v{{ checksum "_cache_v" }}-{{ .Branch }}
          - linear-base-stackcache-{{ arch }}-v{{ checksum "_cache_v" }}-master
          - linear-base-stackcache-{{ arch }}-v{{ checksum "_cache_v" }}-
      - run:
          # --jobs=1 because of limited memory
          name: Build dependencies
          command: |
            stack --no-docker build --test --bench --jobs=1 --only-dependencies --no-haddock linear-base
            find . -name "*.cabal" -o -name "stack.yaml" -type f | xargs sha256sum > /tmp/dps_checksum
      - save_cache:
          key: linear-base-stackcache-{{ arch }}-v{{ checksum "_cache_v" }}-{{ .Branch }}-{{ checksum "/tmp/dps_checksum" }}
          paths:
            - ~/.stack
            - .stack-work
      - run:
          name: Main build
          command: stack --no-docker build --pedantic
      - run:
          name: Test suit
          command: stack --no-docker test --pedantic
