# See https://hub.docker.com/r/tweag/linear-types/
resolver: lts-16.2
compiler: ghc-8.11
allow-newer: true
system-ghc: true

packages:
- '.'

extra-deps:
  - git: https://github.com/tweag/linear-base.git
    commit: 5df446e4c8801cd5509837ca3feea77b5ab08850

nix:
  enable: true
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
